name: atc_whisper
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip
  - pip:
    - numpy
    - transformers
    - pycdlib
    - pyyaml
    - tabulate
    - openai-whisper